-- Migration 0001: identity graph + whatsapp raw landing table.
-- Generated by hand from crm_app/models.py (the source of truth).
-- NOT auto-applied. The app boots `Base.metadata.create_all()` in
-- crm_app/main.py which creates these tables idempotently. Keep this
-- file in sync with the ORM so the schema is reviewable end-to-end.
--
-- Apply manually:
--   sqlite3 crm.db < migrations/0001_identity_and_raw_messages.sql
-- (Safe to run on an already-migrated DB — every CREATE uses IF NOT EXISTS.)

CREATE TABLE IF NOT EXISTS whatsapp_raw_messages (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    group_name        VARCHAR  NOT NULL,
    sender_phone      VARCHAR  NOT NULL,
    sender_name       VARCHAR,
    timestamp         DATETIME NOT NULL,
    body              TEXT     NOT NULL DEFAULT '',
    is_from_me        BOOLEAN  NOT NULL DEFAULT 0,
    message_type      VARCHAR  NOT NULL,
    media_url         TEXT,
    -- Periskope event-driven edit/delete tracking + provider-side stable id
    source_message_id VARCHAR,
    is_edited         BOOLEAN  NOT NULL DEFAULT 0,
    edited_at         DATETIME,
    is_deleted        BOOLEAN  NOT NULL DEFAULT 0,
    deleted_at        DATETIME,
    received_at       DATETIME NOT NULL,
    processed_at      DATETIME,
    resolution_status VARCHAR  NOT NULL DEFAULT 'pending',
    resolved_shop_url VARCHAR  REFERENCES shops(shop_url),
    resolution_method VARCHAR,
    CONSTRAINT uq_whatsapp_raw_messages_natural_key
        UNIQUE (group_name, sender_phone, timestamp, body),
    CONSTRAINT ck_whatsapp_raw_messages_resolution_status
        CHECK (resolution_status IN ('pending','resolved','unresolvable','conflict'))
);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_group_name
    ON whatsapp_raw_messages(group_name);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_sender_phone
    ON whatsapp_raw_messages(sender_phone);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_timestamp
    ON whatsapp_raw_messages(timestamp);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_resolution_status
    ON whatsapp_raw_messages(resolution_status);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_resolved_shop_url
    ON whatsapp_raw_messages(resolved_shop_url);
CREATE INDEX IF NOT EXISTS ix_whatsapp_raw_messages_source_message_id
    ON whatsapp_raw_messages(source_message_id);

CREATE TABLE IF NOT EXISTS identities (
    id    INTEGER PRIMARY KEY AUTOINCREMENT,
    kind  VARCHAR NOT NULL,
    value VARCHAR NOT NULL,
    CONSTRAINT uq_identities_kind_value UNIQUE (kind, value),
    CONSTRAINT ck_identities_kind
        CHECK (kind IN ('shop_url','phone','email','meeting_link','group_name'))
);
CREATE INDEX IF NOT EXISTS ix_identities_kind_value
    ON identities(kind, value);

CREATE TABLE IF NOT EXISTS bindings (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    identity_a_id   INTEGER NOT NULL REFERENCES identities(id),
    identity_b_id   INTEGER NOT NULL REFERENCES identities(id),
    source          VARCHAR NOT NULL,
    confidence      FLOAT   NOT NULL DEFAULT 1.0,
    observed_at     DATETIME NOT NULL,
    evidence_table  VARCHAR,
    evidence_id     VARCHAR,
    CONSTRAINT uq_bindings_natural_key
        UNIQUE (identity_a_id, identity_b_id, source, evidence_id),
    CONSTRAINT ck_bindings_undirected_order
        CHECK (identity_a_id < identity_b_id)
);
CREATE INDEX IF NOT EXISTS ix_bindings_identity_a_id
    ON bindings(identity_a_id);
CREATE INDEX IF NOT EXISTS ix_bindings_identity_b_id
    ON bindings(identity_b_id);
